# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: analytics.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'analytics.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import common_pb2 as common__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0f\x61nalytics.proto\x12\ntelemetryx\x1a\x0c\x63ommon.proto\"d\n\x16\x44\x65tectAnomaliesRequest\x12!\n\x06\x65vents\x18\x01 \x03(\x0b\x32\x11.telemetryx.Event\x12\x12\n\nmodel_name\x18\x02 \x01(\t\x12\x13\n\x0bsensitivity\x18\x03 \x01(\x01\"`\n\x17\x44\x65tectAnomaliesResponse\x12*\n\x07results\x18\x01 \x03(\x0b\x32\x19.telemetryx.AnomalyResult\x12\x19\n\x11inference_time_ms\x18\x02 \x01(\x03\"a\n\rAnomalyResult\x12\x10\n\x08\x65vent_id\x18\x01 \x01(\t\x12\x12\n\nis_anomaly\x18\x02 \x01(\x08\x12\x15\n\ranomaly_score\x18\x03 \x01(\x01\x12\x13\n\x0b\x65xplanation\x18\x04 \x01(\t2\xbe\x01\n\x10\x41nalyticsService\x12Z\n\x0f\x44\x65tectAnomalies\x12\".telemetryx.DetectAnomaliesRequest\x1a#.telemetryx.DetectAnomaliesResponse\x12N\n\x0bHealthCheck\x12\x1e.telemetryx.HealthCheckRequest\x1a\x1f.telemetryx.HealthCheckResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'analytics_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_DETECTANOMALIESREQUEST']._serialized_start=45
  _globals['_DETECTANOMALIESREQUEST']._serialized_end=145
  _globals['_DETECTANOMALIESRESPONSE']._serialized_start=147
  _globals['_DETECTANOMALIESRESPONSE']._serialized_end=243
  _globals['_ANOMALYRESULT']._serialized_start=245
  _globals['_ANOMALYRESULT']._serialized_end=342
  _globals['_ANALYTICSSERVICE']._serialized_start=345
  _globals['_ANALYTICSSERVICE']._serialized_end=535
# @@protoc_insertion_point(module_scope)
