# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: common.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'common.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0c\x63ommon.proto\x12\ntelemetryx\"\xc3\x01\n\x05\x45vent\x12\n\n\x02id\x18\x01 \x01(\t\x12\x12\n\nevent_type\x18\x02 \x01(\t\x12\x11\n\ttimestamp\x18\x03 \x01(\x03\x12\x0e\n\x06source\x18\x04 \x01(\t\x12\x35\n\nattributes\x18\x05 \x03(\x0b\x32!.telemetryx.Event.AttributesEntry\x12\r\n\x05value\x18\x06 \x01(\x01\x1a\x31\n\x0f\x41ttributesEntry\x12\x0b\n\x03key\x18\x01 \x01(\t\x12\r\n\x05value\x18\x02 \x01(\t:\x02\x38\x01\"\x07\n\x05\x45mpty\"\x14\n\x12HealthCheckRequest\"\x90\x01\n\x13HealthCheckResponse\x12=\n\x06status\x18\x01 \x01(\x0e\x32-.telemetryx.HealthCheckResponse.ServingStatus\":\n\rServingStatus\x12\x0b\n\x07UNKNOWN\x10\x00\x12\x0b\n\x07SERVING\x10\x01\x12\x0f\n\x0bNOT_SERVING\x10\x02\x42\x12Z\x10telemetryx/protob\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'common_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'Z\020telemetryx/proto'
  _globals['_EVENT_ATTRIBUTESENTRY']._loaded_options = None
  _globals['_EVENT_ATTRIBUTESENTRY']._serialized_options = b'8\001'
  _globals['_EVENT']._serialized_start=29
  _globals['_EVENT']._serialized_end=224
  _globals['_EVENT_ATTRIBUTESENTRY']._serialized_start=175
  _globals['_EVENT_ATTRIBUTESENTRY']._serialized_end=224
  _globals['_EMPTY']._serialized_start=226
  _globals['_EMPTY']._serialized_end=233
  _globals['_HEALTHCHECKREQUEST']._serialized_start=235
  _globals['_HEALTHCHECKREQUEST']._serialized_end=255
  _globals['_HEALTHCHECKRESPONSE']._serialized_start=258
  _globals['_HEALTHCHECKRESPONSE']._serialized_end=402
  _globals['_HEALTHCHECKRESPONSE_SERVINGSTATUS']._serialized_start=344
  _globals['_HEALTHCHECKRESPONSE_SERVINGSTATUS']._serialized_end=402
# @@protoc_insertion_point(module_scope)
