#!/usr/bin/env python3
"""Generate Python code from Protocol Buffer definitions.

This script:
1. Compiles .proto files to Python using grpc_tools.protoc
2. Fixes import paths to work with the telemetryx package structure

Run from the python/ directory.
"""

import re
import subprocess
import sys
from pathlib import Path


# Directories (relative to python/)
PROTO_DIR = Path("../proto")           # Where .proto files live
OUTPUT_DIR = Path("telemetryx/proto")  # Where to generate Python code

# Proto files to compile
PROTO_FILES = [
    "common.proto",
    "rules.proto",
    "analytics.proto",
]


def run_protoc() -> None:
    """Run the protobuf compiler to generate Python code."""
    print("Compiling Protocol Buffers...")
    
    # Ensure output directory exists
    OUTPUT_DIR.mkdir(parents=True, exist_ok=True)
    
    # Build the protoc command
    proto_paths = [str(PROTO_DIR / f) for f in PROTO_FILES]
    
    cmd = [
        sys.executable, "-m", "grpc_tools.protoc",
        f"-I{PROTO_DIR}",
        f"--python_out={OUTPUT_DIR}",
        f"--grpc_python_out={OUTPUT_DIR}",
        *proto_paths,
    ]
    
    print(f"  Running: {' '.join(cmd)}")
    result = subprocess.run(cmd, capture_output=True, text=True)
    
    if result.returncode != 0:
        print(f"protoc failed:\n{result.stderr}")
        sys.exit(1)
    
    print("✅ Proto compilation complete")


def fix_imports() -> None:
    """Fix import statements in generated files.
    
    The protoc compiler generates imports like:
        import common_pb2 as common__pb2
    
    We need to change them to:
        from telemetryx.proto import common_pb2 as common__pb2
    """
    print("Fixing import paths...")
    
    # Patterns to fix
    # Match: import <name>_pb2 as <alias>
    import_pattern = re.compile(r"^import (\w+_pb2) as (\w+)$", re.MULTILINE)
    
    # Replacement: from telemetryx.proto import <name>_pb2 as <alias>
    def replacement(match: re.Match) -> str:
        module = match.group(1)
        alias = match.group(2)
        return f"from telemetryx.proto import {module} as {alias}"
    
    # Process all generated files
    for py_file in OUTPUT_DIR.glob("*_pb2*.py"):
        content = py_file.read_text()
        original = content
        
        # Apply fix
        content = import_pattern.sub(replacement, content)
        
        if content != original:
            py_file.write_text(content)
            print(f"  Fixed: {py_file.name}")
        else:
            print(f"  Skipped (no changes): {py_file.name}")
    
    print("Import fixes complete")


def create_init_file() -> None:
    """Create/update __init__.py for the proto package."""
    print("Creating __init__.py...")
    
    init_content = '''"""Generated Protocol Buffer code.

Auto-generated by scripts/generate_proto.py - do not edit manually.
"""
'''
    
    init_file = OUTPUT_DIR / "__init__.py"
    init_file.write_text(init_content)
    print(f"  Created: {init_file}")


def main() -> None:
    """Main entry point."""
    print("=" * 60)
    print("TelemetryX Proto Generator")
    print("=" * 60)
    print()
    
    # Check we're in the right directory
    if not Path("pyproject.toml").exists():
        print("Error: Run this script from the python/ directory")
        print("   Usage: python scripts/generate_proto.py")
        sys.exit(1)
    
    # Check proto directory exists
    if not PROTO_DIR.exists():
        print(f"Error: Proto directory not found: {PROTO_DIR}")
        sys.exit(1)
    
    # Run steps
    run_protoc()
    fix_imports()
    create_init_file()
    
    print()
    print("=" * 60)
    print("All done! Generated files in:", OUTPUT_DIR)
    print("=" * 60)


if __name__ == "__main__":
    main()
